# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0058_event_based_hazard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='area_source_discretization',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='correlation_model',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='gmpe_logic_tree',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='grid_spacing',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='imt_l',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='ini_file',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='investigation_time',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='max_distance',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='n_lt_samples',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='oq_id',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='poes',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='quantile_hazard_curves',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='random_seed',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='region',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='rupture_mesh_spacing',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='site_model',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='sites_type',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='sm_logic_tree',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='status',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='truncation_level',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='vs30',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='vs30_clustering',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='vs30type',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='width_of_mfd_bin',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='z1pt0',
        ),
        migrations.RemoveField(
            model_name='event_based_hazard',
            name='z2pt5',
        ),
        migrations.AddField(
            model_name='event_based_hazard',
            name='classical_psha_hazard_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, default=1, serialize=False, to='jobs.Classical_PSHA_Hazard'),
            preserve_default=False,
        ),
    ]
